import { defineAttachmentSource, defineRpc } from "@getpaseo/plugin";
import { z } from "zod";

export const promptId = z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/).max(120);
export const settingsSchema = z.object({ directory: z.string().min(1), gitEnabled: z.boolean() });
export const promptSchema = z.object({ id: promptId, title: z.string(), content: z.string(), revision: z.string(), updatedAt: z.string(), archived: z.boolean() });
export const versionSchema = z.object({ filename: z.string(), version: z.number().int(), createdAt: z.string() });
export type Prompt = z.infer<typeof promptSchema>;
export type LibrarySettings = z.infer<typeof settingsSchema>;
export type Version = z.infer<typeof versionSchema>;
export const importResultSchema = z.object({ imported: z.array(promptId), skipped: z.array(z.object({ source: z.string(), reason: z.string() })) });
export type ImportResult = z.infer<typeof importResultSchema>;
export const importPrompts = defineRpc({ name: "prompts.import", input: z.object({ paths: z.array(z.string().min(1)).max(100).default([]), files: z.array(z.object({ name: z.string().min(1).max(1024), content: z.string().max(512_000) })).max(100).default([]) }), output: importResultSchema });
const empty = z.object({});
export const getSettings = defineRpc({ name: "library.settings", input: empty, output: settingsSchema });
export const saveSettings = defineRpc({ name: "library.configure", input: settingsSchema, output: settingsSchema });
export const listPrompts = defineRpc({ name: "prompts.list", input: z.object({ query: z.string().default(""), archived: z.boolean().default(false) }), output: z.array(promptSchema.omit({ content: true })) });
export const readPrompt = defineRpc({ name: "prompts.read", input: z.object({ id: promptId }), output: promptSchema });
export const savePrompt = defineRpc({ name: "prompts.save", input: z.object({ id: promptId.optional(), name: z.string().min(1).max(120), content: z.string().min(1).max(512_000), revision: z.string().nullable() }), output: promptSchema });
export const archivePrompt = defineRpc({ name: "prompts.archive", input: z.object({ id: promptId, revision: z.string() }), output: empty });
export const listVersions = defineRpc({ name: "prompts.versions", input: z.object({ id: promptId }), output: z.array(versionSchema) });
export const readVersion = defineRpc({ name: "prompts.version", input: z.object({ id: promptId, filename: z.string() }), output: z.object({ content: z.string() }) });
export const restoreVersion = defineRpc({ name: "prompts.restore", input: z.object({ id: promptId, filename: z.string(), revision: z.string().nullable() }), output: promptSchema });
export const gitStatusSchema = z.object({ initialized: z.boolean(), branch: z.string(), remote: z.string(), changes: z.number().int(), message: z.string() });
export const getGitStatus = defineRpc({ name: "library.git-status", input: empty, output: gitStatusSchema });
export const initGit = defineRpc({ name: "library.git-init", input: z.object({ remote: z.string() }), output: gitStatusSchema });
export const syncGit = defineRpc({ name: "library.git-sync", input: empty, output: gitStatusSchema });
export const searchPrompts = defineRpc({ name: "prompts.search", input: z.object({ query: z.string() }), output: z.object({ items: z.array(z.object({ id: z.string(), identifier: z.string(), url: z.string().url(), title: z.string(), subtitle: z.string(), text: z.string(), resourceType: z.string() })) }) });
export const promptAttachment = defineAttachmentSource({ id: "prompts", title: "Saved prompt", icon: "NotebookPen", pickerTitle: "Attach saved prompt", searchPlaceholder: "Search titles, filenames, or prompt content", search: searchPrompts });
